
   
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prtwebsite
  labels:
    app: website
spec:
  replicas: 5
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website 
    spec:
      containers:
      - name: webserver
        image: ashwathy/website-prt-org
        ports:
        - containerPort: 80
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: website-service
spec:
  selector:
    app: website 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 31110

